### ISSUE TITLE
Revise 'Users' table to include a password column (?)

### ISSUE THREAD

**Issue by Dunn-Austen** [Dustin-Mikusko/palette-picker-be#15]
- I'm actually not totally sure about this. I'm still getting used to back-end work. Relational databases are vulnerable to SQL injection attacks, yeah? Does that mean that we need to cache the password values elsewhere?

**Comment by Dustin-Mikusko** [comment]
I totally forgot to add in a password field for the users. Good catch. As far as caching it somewhere else, probably, but I'm not sure how to do that currently.

**Comment by Dunn-Austen** [comment]
Closing out this issue. We changed out table setup and will no longer have a users table. Projects, palettes, and colors are the finalized choices
